package views;

import controller.UsuarioController;
import entity.Usuario;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import views.MainFrame;

public class LoginFrame extends javax.swing.JFrame {

    private javax.persistence.EntityManagerFactory emf;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Login - Videoclub DAW");
        emf = javax.persistence.Persistence.createEntityManagerFactory("videoclubdaw");

        // Look & Feel Nimbus
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
        }

        // Icono redimensionado
        ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/img/film.png"));
        // Escalado exacto al tamaño del JLabel
        // Escalado exacto al tamaño del JLabel
        Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                lblIcono.getWidth(), lblIcono.getHeight(), Image.SCALE_SMOOTH);
        lblIcono.setIcon(new ImageIcon(imagenEscalada));
        this.repaint();

        // Fuentes y colores modernos
        java.awt.Font fuenteTitulo = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22);
        java.awt.Font fuenteCampos = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16);

        txtUsuario.setPreferredSize(new java.awt.Dimension(150, 30));
        jPasswordField.setPreferredSize(new java.awt.Dimension(150, 30));
//        txtUsuario.setColumns(16);
//        jPasswordField.setColumns(16);
        usuarioLabel.setFont(fuenteCampos);
        passwordLabel.setFont(fuenteCampos);
        btnEntrar.setFont(fuenteCampos);
        btnRegistrar.setFont(fuenteCampos);
        btnOlvidasteContrasena.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        lblIcono.setFont(fuenteTitulo);

        getContentPane().setBackground(new java.awt.Color(245, 245, 245)); // Fondo claro

        lblMensaje.setText(""); // Sin mensaje al iniciar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcono = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        btnOlvidasteContrasena = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIcono.setText("lblIcono");

        usuarioLabel.setText("Usuario:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        passwordLabel.setText("Contraseña:");

        jPasswordField.setText("JpassField");
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        btnOlvidasteContrasena.setText("Olvidaste la contraseña?");
        btnOlvidasteContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOlvidasteContrasenaActionPerformed(evt);
            }
        });

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnEntrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnOlvidasteContrasena))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnRegistrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passwordLabel)
                                    .addComponent(usuarioLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMensaje)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addComponent(lblMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEntrar)
                .addGap(18, 18, 18)
                .addComponent(btnOlvidasteContrasena)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        JTextField txtNuevoUsuario = new JTextField();
        JPasswordField txtNuevaPassword = new JPasswordField();
        JTextField txtNuevoEmail = new JTextField();
        Object[] campos = {
            "Nombre de usuario:", txtNuevoUsuario,
            "Contraseña:", txtNuevaPassword,
            "Email:", txtNuevoEmail
        };
        int opcion = JOptionPane.showConfirmDialog(this, campos, "Registrar nuevo usuario", JOptionPane.OK_CANCEL_OPTION);
        if (opcion != JOptionPane.OK_OPTION) {
            return;
        }

        String nombre = txtNuevoUsuario.getText().trim();
        String password = new String(txtNuevaPassword.getPassword()).trim();
        String email = txtNuevoEmail.getText().trim();

        // Validaciones básicas
        if (nombre.isEmpty() || password.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }
        if (!nombre.matches("[A-Za-z0-9]+")) {
            JOptionPane.showMessageDialog(this, "El nombre de usuario solo puede contener letras y números.");
            return;
        }
        if (!email.matches("^[\\w\\.-]+@[\\w\\.-]+\\.\\w+$")) {
            JOptionPane.showMessageDialog(this, "Email no válido.");
            return;
        }

        UsuarioController usuarioController = new UsuarioController(emf);
        java.util.List<Usuario> usuarios = usuarioController.listarUsuarios();
        for (Usuario u : usuarios) {
            if (u.getNombre().equals(nombre)) {
                JOptionPane.showMessageDialog(this, "El nombre de usuario ya existe.");
                return;
            }
            if (u.getEmail().equals(email)) {
                JOptionPane.showMessageDialog(this, "El email ya está registrado.");
                return;
            }
        }
        Usuario nuevoUsuario = new Usuario();
        nuevoUsuario.setNombre(nombre);
        nuevoUsuario.setPassword(password);
        nuevoUsuario.setEmail(email);
        usuarioController.crearUsuario(nuevoUsuario);
        JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.");

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnOlvidasteContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlvidasteContrasenaActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(this, "Introduce tu nombre de usuario:");
        if (nombre == null || nombre.trim().isEmpty()) {
            return;
        }

        String nuevaContrasena = JOptionPane.showInputDialog(this, "Introduce la nueva contraseña:");
        if (nuevaContrasena == null || nuevaContrasena.trim().isEmpty()) {
            return;
        }

        UsuarioController usuarioController = new UsuarioController(emf);
        java.util.List<Usuario> usuarios = usuarioController.listarUsuarios();
        Usuario usuarioEncontrado = null;
        for (Usuario u : usuarios) {
            if (u.getNombre().equals(nombre)) {
                usuarioEncontrado = u;
                break;
            }
        }
        if (usuarioEncontrado != null) {
            usuarioEncontrado.setPassword(nuevaContrasena);
            usuarioController.actualizarUsuario(usuarioEncontrado);
            JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado.");
        }

    }//GEN-LAST:event_btnOlvidasteContrasenaActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        String nombre = txtUsuario.getText().trim();
        String password = new String(jPasswordField.getPassword()).trim();

        UsuarioController usuarioController = new UsuarioController(emf);
        java.util.List<Usuario> usuarios = usuarioController.listarUsuarios();

        boolean loginCorrecto = false;
        Usuario usuarioLogueado = null;
        for (Usuario u : usuarios) {
            if (u.getNombre().equals(nombre) && u.getPassword().equals(password)) {
                usuarioLogueado = u;
                break;
            }
        }

        if (usuarioLogueado != null) {
            MainFrame mainFrame = new MainFrame(usuarioLogueado);
            mainFrame.setVisible(true);
            this.dispose();
        } else {
            lblMensaje.setForeground(new java.awt.Color(220, 53, 69)); // Rojo Bootstrap
            lblMensaje.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
            lblMensaje.setText("Usuario o contraseña incorrectos.");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnOlvidasteContrasena;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
    // Método main para lanzar la ventana
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
}
